name: Load Test with Vegeta

on:
  push:
    branches:
      - main  # Запуск тестов при пуше в ветку main
  pull_request:
    branches:
      - main  # Запуск тестов при создании PR в ветку main

jobs:
  vegeta-load-test:
    runs-on: ubuntu-latest  # Используем виртуальную машину Ubuntu

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Обновили версию actions/checkout

      - name: Set up Vegeta
        run: |
          # Скачиваем и устанавливаем Vegeta
          echo "Downloading Vegeta..."
          wget https://github.com/tsenart/vegeta/releases/download/v12.1.0/vegeta-12.1.0-linux-amd64.tar.gz
          if [ $? -ne 0 ]; then echo "Failed to download Vegeta"; exit 1; fi  # Проверяем успех скачивания
          echo "Extracting Vegeta..."
          tar -xvf vegeta-12.1.0-linux-amd64.tar.gz
          sudo mv vegeta /usr/local/bin
          if [ $? -ne 0 ]; then echo "Failed to install Vegeta"; exit 1; fi  # Проверяем успешную установку

      - name: Prepare Targets for Load Test
        run: |
          # Создаем файл с целями для теста
          echo "GET https://reu.rf" > targets.txt  # Цель - главная страница сайта reu.rf

      - name: Run Load Test
        run: |
          # Запускаем нагрузочный тест через Vegeta
          echo "Running Load Test..."
          vegeta attack -rate=100 -duration=30s -targets=targets.txt | tee results.bin | vegeta report
          if [ $? -ne 0 ]; then echo "Vegeta test failed"; exit 1; fi  # Проверка на ошибки

      - name: Upload Test Results
        uses: actions/upload-artifact@v3  # Обновленная версия действия для загрузки артефактов
        with:
          name: load-test-results
          path: results.bin  # Загружаем результаты теста как артефакт